<?php

namespace AppBundle\Repository;

/**
 * AmistadUsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmistadUsuarioRepository extends \Doctrine\ORM\EntityRepository
{
}
