<?php

namespace AppBundle\Repository;

/**
 * ContactoEscaleraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactoEscaleraRepository extends \Doctrine\ORM\EntityRepository
{
}
