<?php

namespace AppBundle\Repository;

/**
 * EscaleraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscaleraRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerEventosXContacto($contacto)
	{
		$consulta = $this->getEntityManager()
					->createQuery('
						SELECT e FROM AppBundle:Escalera
							JOIN 
					');

	}
}
