<?php

namespace AppBundle\Repository;

/**
 * EscaleraAspectosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscaleraAspectosRepository extends \Doctrine\ORM\EntityRepository
{
}
