<?php

namespace AppBundle\Repository;

/**
 * EscaleraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscaleraRepository extends \Doctrine\ORM\EntityRepository
{
	public function obtenerEventosXContacto($contacto)
	{
		$consulta = $this->getEntityManager()
					->createQuery('
						SELECT e,a,c FROM AppBundle:Escalera e
							JOIN e.aspectos a
							LEFT JOIN a.contactosEscalera c 
							WHERE c.id = :contacto
					');
		$consulta->setParameter('contacto', $contacto);			
		return $consulta->getResult();
	}
}

