<?php

namespace AppBundle\Repository;

/**
 * EscaleraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscaleraRepository extends \Doctrine\ORM\EntityRepository
{
}
